# Generated by Django 4.0.3 on 2022-03-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pshop', '0002_remove_servico_endereco_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fone',
            new_name='telefone',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(max_length=14),
        ),
    ]
