# Generated by Django 4.0.3 on 2022-03-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pshop', '0003_rename_fone_cliente_telefone_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho'), ('N', 'Outro')], max_length=1),
        ),
    ]
