# Generated by Django 4.0.3 on 2022-03-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pshop', '0004_alter_pet_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.AddField(
            model_name='servico',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pshop.cliente'),
        ),
        migrations.RemoveField(
            model_name='servico',
            name='pet',
        ),
        migrations.AddField(
            model_name='servico',
            name='pet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pshop.pet'),
        ),
    ]
