# Generated by Django 4.0.3 on 2022-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pshop', '0005_remove_servico_cliente_servico_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('p', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('N', 'Outro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tipo',
            field=models.CharField(choices=[('Gato', 'Gato(a)'), ('Cachorro', 'Cachorro(a)'), ('Outro', 'Outro')], max_length=11),
        ),
        migrations.AlterField(
            model_name='servico',
            name='formaPag',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartao', 'Cartão'), ('PIX', 'PIX'), ('Deposito', 'Depósito'), ('Outro', 'Outro')], max_length=8),
        ),
    ]
