# Generated by Django 4.0 on 2022-03-22 00:37

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created',
                 model_utils.fields.AutoCreatedField(
                     default=django.utils.timezone.now,
                     editable=False,
                     verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(
                     default=django.utils.timezone.now,
                     editable=False,
                     verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('slug',
                 autoslug.fields.AutoSlugField(editable=False,
                                               populate_from='name',
                                               unique=True)),
                ('image',
                 models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2,
                                              max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', ),
            },
        ),
    ]
